name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs on everday 12:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in my blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.wuzhiping.top/atom.xml"
          enable_keepalive: true
          gh_token:   ${{ secrets.GITHUB_TOKEN }}
          commit_message: 🚀 Updated with the latest blog posts
          committer_username: frankwuzp
          committer_email: me@wuzhiping.top
          
